apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.labels.deploymentLabel }}
  namespace: {{ .Values.backend.metadata.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.labels.appLabel }}
    spec:
      containers:
        - name: {{ .Values.backend.image.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.backend.containerPort | default "8080" }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.backend.databaseConfig.POSTGRES_HOST }}"
            - name: POSTGRES_DB
              value: "{{ .Values.backend.databaseConfig.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.backend.databaseConfig.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.backend.databaseConfig.POSTGRES_PASSWORD }}"
