apiVersion: v1
kind: Service
metadata:
  name: crud-app-backend
spec:
  selector:
    app: crud-app-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
  type: {{ .Values.backend.service.type }}
