apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.labels.serviceLabel }}
  namespace: {{ .Values.backend.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.backend.labels.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
  type: {{ .Values.backend.service.type }}
